name: go build

on:
  # push:
  #   branches: [ development ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/syedalisait/goprivaterepo"
      GH_ACCESS_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Prepare Global Git Configuration
        run: git config --global url.ssh://$GITHUB_TOKEN@github.com/.insteadOf https://github.com/

      - name: Build
        run: go build -v ./...

    # - name: Test
    #   run: go test -v ./...