name: go build

on:
  # push:
  #   branches: [ development ]
  pull_request:
    branches: [ master ]

jobs:
  # This is the job ID
  build-and-test:
    name: Build and Test
    # The machine we have chosen to run the job is "ubuntu-latest"
    runs-on: ubuntu-latest

    # Initialize postgres as a service since we will be running tests
    # This runs as a separate container inside "ubuntu-latest"
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

#      - name: Set up Postgress
#        uses: harmon758/postgresql-action@v1
#        with:
#          postgresql version: '14.2'
#          postgresql password: 'root'
#          postgresql user: 'root'

      - name: Set up DB
        env:
          PGPASSWORD: root
        run: psql -U root --host=localhost -c "CREATE USER dev WITH SUPERUSER;"

      - name: Git Configuration
        env:
          GH_ACTION_TOKEN: "${{ secrets.GH_ACTION_TOKEN }}"
        run: git config --global url.https://$GH_ACTION_TOKEN@github.com/.insteadOf https://github.com/

      - name: Configure GOPRIVATE and GO111MODULE before build
        run: |
          go env -w GO111MODULE="on"
          go env -w GOPRIVATE="github.com/syedalisait/goprivaterepo"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...